format_version: 10
pipelines:
  local-build:
    group: prod-demo
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2d73326:
        git: https://github.com/bshurick/production-demo.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          make-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: make
                run_if: passed
