format_version: 10
pipelines:
  deploy:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      build:
        ignore_for_scheduling: false
        pipeline: build
        stage: test
      git-4999863:
        git: https://github.com/bshurick/production-demo.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        environment_variables:
          MODEL_LOC: /Users/shurickb/ProdDemo/production-demo/data/trained_model
        jobs:
          make-build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - data
                command: mkdir
                run_if: passed
            - exec:
                arguments:
                - -c
                - cp $MODEL_LOC data/trained_model
                command: sh
                run_if: passed
            - exec:
                arguments:
                - build
                command: make
                run_if: passed
    - launch:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          launch-docker:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - login
                command: docker
                run_if: passed
            - exec:
                arguments:
                - deploy
                command: make
                run_if: passed
