format_version: 10
pipelines:
  integration-test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      deploy:
        ignore_for_scheduling: false
        pipeline: deploy
        stage: launch
      git-d646ae5:
        git: https://github.com/bshurick/production-demo
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          pytest:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                - -q
                - -U
                - pytest
                command: pip3
                run_if: passed
            - exec:
                arguments:
                - -vv
                - test_integ
                command: pytest
                run_if: passed
