format_version: 10
pipelines:
  integration-test:
    group: prod-demo
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      packaging:
        ignore_for_scheduling: false
        pipeline: packaging
        stage: build
      deploy:
        ignore_for_scheduling: false
        pipeline: deploy
        stage: launch-container
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          make-integ-test:
            timeout: 0
            tasks:
            - fetch:
                is_file: true
                source: Makefile
                destination: ''
                pipeline: packaging
                stage: build
                job: docker-build
                artifact_origin: gocd
                run_if: passed
            - fetch:
                is_file: false
                source: test_integ
                destination: ''
                pipeline: packaging
                stage: build
                job: docker-build
                artifact_origin: gocd
                run_if: passed
            - exec:
                arguments:
                - integ-test
                command: make
                run_if: passed
