format_version: 10
pipelines:
  packaging:
    group: prod-demo
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 3
    materials:
      git-b0b83b7:
        git: https://github.com/bshurick/production-demo.git
        shallow_clone: true
        auto_update: true
        branch: main
      build-test:
        ignore_for_scheduling: false
        pipeline: build-test
        stage: test
      train:
        ignore_for_scheduling: false
        pipeline: train-eval
        stage: train
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          docker-build:
            timeout: 0
            artifacts:
            - build:
                source: configuration/prod-demo-build.tar.gz
                destination: ''
            - build:
                source: Makefile
                destination: ''
            - build:
                source: test_integ
                destination: ''
            - build:
                source: data
                destination: ''           
            tasks:
            - fetch:
                is_file: false
                source: data
                destination: ''
                pipeline: train-eval
                stage: train
                job: run-train
                artifact_origin: gocd
                run_if: passed                 
            - exec:
                arguments:
                - build
                command: make
                run_if: passed
