format_version: 10
pipelines:
  train-eval:
    group: prod-demo
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-5d31a7d:
        git: https://github.com/bshurick/production-demo.git
        shallow_clone: true
        auto_update: true
        branch: main
      build-test:
        ignore_for_scheduling: false
        pipeline: build-test
        stage: test
    stages:
    - train:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-train:
            timeout: 0
            artifacts:
            - build:
                source: data/trained_model
                destination: ''
            tasks:
            - exec:
                arguments:
                - train
                command: make
                run_if: passed
            - exec:
                arguments:
                - evaluate
                command: make
                run_if: passed
