FROM gocd/gocd-agent-ubuntu-20.04:v22.1.0
ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    libgomp1 \
    python3.9 \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

USER go