FROM gocd/gocd-agent-ubuntu-20.04:v22.1.0
ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    libgomp1 \
    python3.9 \
    python3-dev \
    make \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
RUN python get-pip.py
ENV PATH="/home/go/.local/bin:$PATH"

USER go